### PR TITLE
Fix NPE in ordered-set

### LINKED ISSUE #73: OrderedSet/hashCode throws an NPE if it contains nil
Repo:

```clojure
(.hashCode (os/ordered-set nil :a :b :c))
```

Stack trace:

```clojure
#error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [flatland.ordered.set.OrderedSet$fn__4371 invoke "set.clj" 59]}]
 :trace
 [[flatland.ordered.set.OrderedSet$fn__4371 invoke "set.clj" 59]
  [clojure.core$map$fn__5935 invoke "core.clj" 2770]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5467 invokeStatic "core.clj" 139]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 24]
  [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8178$G__8173__8191 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6882]
  [clojure.core$reduce invoke "core.clj" 6868]
  [flatland.ordered.set.OrderedSet hashCode "set.clj" 59]
...
```

Comes from unconditionally calling `.hashCode` on all of the contained items:

https://github.com/clj-commons/ordered/blob/8cc133da590c2dd84e370899be03b26958a6a27f/src/flatland/ordered/set.clj#L59

I believe this could be solved by either using `clojure.core/hash` or by changing to a `keep` (which is fine because the hash of `nil` is 0):

```clojure
(reduce + (keep #(when % (.hashCode ^Object %)) (.seq this))))

### PR DESCRIPTION
**Pull request by NoahTheDuke**
I fixed the existing `flatland.ordered.set-test/nil-hash-code-npe` test as it was incorrectly written and never actually checked that ordered sets can contain nulls. Oops!

Closes https://github.com/clj-commons/ordered/issues/73

### CODE REVIEW

**Review by jafingerhut — APPROVED** [review]
LGTM

File: src/flatland/ordered/set.clj [hunk 1]
```diff
@@ -56,7 +56,7 @@
   (toString [this]
     (str "#{" (clojure.string/join " " (map str this)) "}"))
   (hashCode [this]
-    (reduce + (map #(.hashCode ^Object %) (.seq this))))
+    (reduce + (keep #(when % (.hashCode ^Object %)) (.seq this))))
```
Comment (borkdude) [inline src/flatland/ordered/set.clj:59]: This doesn't look good to me, since `false` will be treated the same way here as `nil`

Comment (borkdude) [reply src/flatland/ordered/set.clj:59]: cc @jafingerhut

Comment (jafingerhut) [reply src/flatland/ordered/set.clj:59]: Good catch.  Highly recomended to add an explicit test case with `false` as an element of a set, to confirm, and then fix the expected issue that such a test case should find.
